### PR TITLE
image fixes

### PR DESCRIPTION
**Pull request by EG-tech**
@dylanlorenz here's another example of how the PR + merge process can work:

1. I made a branch for myself (only an option for you and me as maintainers on the repository - other contributors/students would just fork instead)
2. I made two separate commits on my branch for clarity's sake, as they represent two distinct fixes (the first deletes a couple duplicate images that I think were accidentally uploaded to the top level of the repository rather than into the `images/Video` sub-folder; the second fixes I only just noticed which is that file names with colons like `1:8_trs_cork.jpg` are not compliant on Windows, so trying to clone and work with the cable-bible in a local copy with GitHub Desktop on Windows fails)
3. I'm opening a pull request and using the "Reviewer" function to request your approval before (either you or I) merge the PR. As maintainers we both have the power to merge our own pull requests, but the "Reviewer" request is a nice courtesy feature, and the students could use it to immediately bring their PRs to your and/or my attention
4. As a maintainer you should now be able to "Review" this PR: you can approve and merge it yourself, you could just approve of it (and then I'll merge it), you can comment on particular changes and request further commits/edits before merging, or you can reject/close the PR outright

### CODE REVIEW

**Review by dylanlorenz — COMMENTED** [review]
Changes look good. Thanks!

**Comment by EG-tech** [comment]
fyi you closed the pull request without merging it again! so the fixes didn't actually get applied to the master branch and the live site

(you should see a green "Merge pull request" button above this - click that, not the "Close with comment" button below the comment box)

**Comment by dylanlorenz** [comment]
Sorry about that. Just merged it

**Comment by EG-tech** [comment]
no worries!!

**Pull request merged**
