### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by dylanlorenz**
Updated PATA to PATA (IDE). 

Added definition of IDE and made grammar change. 

Updated poster frame image to IDE cork, rather than IDE bottle.

### CODE REVIEW

**Comment by dylanlorenz** [comment]
@EG-tech This is a proposed update to the PATA cable section that I marked for your review

**Comment by EG-tech** [comment]
@dylanlorenz I got the request to review but then you closed the PR so can't review + merge - are you saving this actual edit for the workshop?

**Comment by dylanlorenz** [comment]
@EG-tech I didn't mean to close it, I was attempting to try out the review function. I tried to rename the branch and it apparently closed the request

**Review by EG-tech — APPROVED** [review]
looks good to me!

only thing is the commit message mentions swapping the poster image, but it doesn't look like that line got edited? (should be line 1405). it's already the cork image either way so doesn't matter either way, just curious

**Pull request merged**
